export default [
  {
    label: "通用图标",
    list: [
      "iconfont iconfont-bulb",
      "iconfont iconfont-experiment",
      "iconfont iconfont-bell",
      "iconfont iconfont-trophy",
      "iconfont iconfont-rest",
      "iconfont iconfont-USB",
      "iconfont iconfont-skin",
      "iconfont iconfont-home",
      "iconfont iconfont-bank",
      "iconfont iconfont-filter",
      "iconfont iconfont-funnelplot",
      "iconfont iconfont-like",
      "iconfont iconfont-unlike",
      "iconfont iconfont-unlock",
      "iconfont iconfont-lock",
      "iconfont iconfont-customerservice",
      "iconfont iconfont-flag",
      "iconfont iconfont-moneycollect",
      "iconfont iconfont-medicinebox",
      "iconfont iconfont-shop",
      "iconfont iconfont-rocket",
      "iconfont iconfont-shopping",
      "iconfont iconfont-folder",
      "iconfont iconfont-folder-open",
      "iconfont iconfont-folder-add",
      "iconfont iconfont-deploymentunit",
      "iconfont iconfont-accountbook",
      "iconfont iconfont-contacts",
      "iconfont iconfont-carryout",
      "iconfont iconfont-calendar-check",
      "iconfont iconfont-calendar",
      "iconfont iconfont-scan",
      "iconfont iconfont-select",
      "iconfont iconfont-boxplot",
      "iconfont iconfont-build",
      "iconfont iconfont-sliders",
      "iconfont iconfont-laptop",
      "iconfont iconfont-barcode",
      "iconfont iconfont-camera",
      "iconfont iconfont-cluster",
      "iconfont iconfont-gateway",
      "iconfont iconfont-car",
      "iconfont iconfont-printer",
      "iconfont iconfont-read",
      "iconfont iconfont-cloud-server",
      "iconfont iconfont-cloud",
      "iconfont iconfont-cloud-download",
      "iconfont iconfont-cloud-sync",
      "iconfont iconfont-video",
      "iconfont iconfont-notification",
      "iconfont iconfont-sound",
      "iconfont iconfont-radarchart",
      "iconfont iconfont-qrcode",
      "iconfont iconfont-fund",
      "iconfont iconfont-image",
      "iconfont iconfont-mail",
      "iconfont iconfont-table",
      "iconfont iconfont-idcard",
      "iconfont iconfont-alipay",
      "iconfont iconfont-creditcard",
      "iconfont iconfont-taobao",
      "iconfont iconfont-heart",
      "iconfont iconfont-zhihu",
      "iconfont iconfont-block",
      "iconfont iconfont-HTML",
      "iconfont iconfont-error",
      "iconfont iconfont-linkedin",
      "iconfont iconfont-gold",
      "iconfont iconfont-facebook",
      "iconfont iconfont-heatmap",
      "iconfont iconfont-skype",
      "iconfont iconfont-wifi",
      "iconfont iconfont-CodeSandbox",
      "iconfont iconfont-attachment",
      "iconfont iconfont-chrome",
      "iconfont iconfont-edit",
      "iconfont iconfont-codepen",
      "iconfont iconfont-key",
      "iconfont iconfont-aliwangwang",
      "iconfont iconfont-api",
      "iconfont iconfont-apple",
      "iconfont iconfont-disconnect",
      "iconfont iconfont-android",
      "iconfont iconfont-highlight",
      "iconfont iconfont-sketch",
      "iconfont iconfont-monitor",
      "iconfont iconfont-Gitlab",
      "iconfont iconfont-link",
      "iconfont iconfont-dribbble",
      "iconfont iconfont-man",
      "iconfont iconfont-instagram",
      "iconfont iconfont-percentage",
      "iconfont iconfont-reddit",
      "iconfont iconfont-pushpin",
      "iconfont iconfont-windows",
      "iconfont iconfont-phone",
      "iconfont iconfont-yuque",
      "iconfont iconfont-shake",
      "iconfont iconfont-Youtube",
      "iconfont iconfont-tag",
      "iconfont iconfont-wrench",
      "iconfont iconfont-tags",
      "iconfont iconfont-scissor",
      "iconfont iconfont-mr",
      "iconfont iconfont-share",
      "iconfont iconfont-branches",
      "iconfont iconfont-fork",
      "iconfont iconfont-shrink",
      "iconfont iconfont-arrawsalt",
      "iconfont iconfont-verticalright",
      "iconfont iconfont-verticalleft",
      "iconfont iconfont-right",
      "iconfont iconfont-left",
      "iconfont iconfont-up",
      "iconfont iconfont-down",
      "iconfont iconfont-fullscreen",
      "iconfont iconfont-fullscreen-exit",
      "iconfont iconfont-doubleleft",
      "iconfont iconfont-doubleright",
      "iconfont iconfont-arrowright",
      "iconfont iconfont-arrowup",
      "iconfont iconfont-arrowleft",
      "iconfont iconfont-arrowdown",
      "iconfont iconfont-upload",
      "iconfont iconfont-colum-height",
      "iconfont iconfont-vertical-align-botto",
      "iconfont iconfont-vertical-align-middl",
      "iconfont iconfont-totop",
      "iconfont iconfont-vertical-align-top",
      "iconfont iconfont-download",
      "iconfont iconfont-sort-descending",
      "iconfont iconfont-sort-ascending",
      "iconfont iconfont-fall",
      "iconfont iconfont-swap",
      "iconfont iconfont-stock",
      "iconfont iconfont-rise",
      "iconfont iconfont-indent",
      "iconfont iconfont-outdent",
      "iconfont iconfont-menu",
      "iconfont iconfont-unorderedlist",
      "iconfont iconfont-orderedlist",
      "iconfont iconfont-align-right",
      "iconfont iconfont-align-center",
      "iconfont iconfont-align-left",
      "iconfont iconfont-pic-center",
      "iconfont iconfont-pic-right",
      "iconfont iconfont-pic-left",
      "iconfont iconfont-bold",
      "iconfont iconfont-font-colors",
      "iconfont iconfont-exclaimination",
      "iconfont iconfont-check-circle",
      "iconfont iconfont-font-size",
      "iconfont iconfont-CI",
      "iconfont iconfont-infomation",
      "iconfont iconfont-Dollar",
      "iconfont iconfont-line-height",
      "iconfont iconfont-compass",
      "iconfont iconfont-strikethrough",
      "iconfont iconfont-close-circle",
      "iconfont iconfont-underline",
      "iconfont iconfont-frown",
      "iconfont iconfont-number",
      "iconfont iconfont-info-circle",
      "iconfont iconfont-italic",
      "iconfont iconfont-left-circle",
      "iconfont iconfont-code",
      "iconfont iconfont-down-circle",
      "iconfont iconfont-column-width",
      "iconfont iconfont-EURO",
      "iconfont iconfont-check",
      "iconfont iconfont-copyright",
      "iconfont iconfont-ellipsis",
      "iconfont iconfont-zoomout",
      "iconfont iconfont-minus-circle",
      "iconfont iconfont-dash",
      "iconfont iconfont-apartment",
      "iconfont iconfont-meh",
      "iconfont iconfont-close",
      "iconfont iconfont-audio",
      "iconfont iconfont-plus-circle",
      "iconfont iconfont-enter",
      "iconfont iconfont-play-circle",
      "iconfont iconfont-line",
      "iconfont iconfont-robot",
      "iconfont iconfont-question-circle",
      "iconfont iconfont-minus",
      "iconfont iconfont-zoomin",
      "iconfont iconfont-Pound",
      "iconfont iconfont-question",
      "iconfont iconfont-right-circle",
      "iconfont iconfont-rollback",
      "iconfont iconfont-smile",
      "iconfont iconfont-bug",
      "iconfont iconfont-trademark",
      "iconfont iconfont-pause",
      "iconfont iconfont-audiostatic",
      "iconfont iconfont-time-circle",
      "iconfont iconfont-comment",
      "iconfont iconfont-timeout",
      "iconfont iconfont-crown",
      "iconfont iconfont-earth",
      "iconfont iconfont-drag",
      "iconfont iconfont-verified",
      "iconfont iconfont-desktop",
      "iconfont iconfont-up-circle",
      "iconfont iconfont-gift",
      "iconfont iconfont-videocameraadd",
      "iconfont iconfont-warning-circle",
      "iconfont iconfont-stop",
      "iconfont iconfont-switchuser",
      "iconfont iconfont-sync",
      "iconfont iconfont-fire",
      "iconfont iconfont-whatsapp",
      "iconfont iconfont-transaction",
      "iconfont iconfont-thunderbolt",
      "iconfont iconfont-appstoreadd",
      "iconfont iconfont-undo",
      "iconfont iconfont-redo",
      "iconfont iconfont-reload",
      "iconfont iconfont-reloadtime",
      "iconfont iconfont-message",
      "iconfont iconfont-dashboard",
      "iconfont iconfont-issuesclose",
      "iconfont iconfont-poweroff",
      "iconfont iconfont-logout",
      "iconfont iconfont-search",
      "iconfont iconfont-piechart",
      "iconfont iconfont-retweet",
      "iconfont iconfont-setting",
      "iconfont iconfont-login",
      "iconfont iconfont-eye",
      "iconfont iconfont-edit-square",
      "iconfont iconfont-swap-right",
      "iconfont iconfont-export",
      "iconfont iconfont-swap-left",
      "iconfont iconfont-save",
      "iconfont iconfont-woman",
      "iconfont iconfont-Import",
      "iconfont iconfont-plus",
      "iconfont iconfont-appstore",
      "iconfont iconfont-close-square",
      "iconfont iconfont-eye-close",
      "iconfont iconfont-down-square",
      "iconfont iconfont-clear",
      "iconfont iconfont-layout",
      "iconfont iconfont-collapse",
      "iconfont iconfont-left-square",
      "iconfont iconfont-expand",
      "iconfont iconfont-play-square",
      "iconfont iconfont-deletecolumn",
      "iconfont iconfont-control",
      "iconfont iconfont-merge-cells",
      "iconfont iconfont-codelibrary",
      "iconfont iconfont-detail",
      "iconfont iconfont-rotate-left",
      "iconfont iconfont-minus-square",
      "iconfont iconfont-rotate-right",
      "iconfont iconfont-plus-square",
      "iconfont iconfont-insertrowbelow",
      "iconfont iconfont-right-square",
      "iconfont iconfont-insertrowabove",
      "iconfont iconfont-project",
      "iconfont iconfont-table1",
      "iconfont iconfont-wallet",
      "iconfont iconfont-solit-cells",
      "iconfont iconfont-up-square",
      "iconfont iconfont-formatpainter",
      "iconfont iconfont-calculator",
      "iconfont iconfont-insertrowright",
      "iconfont iconfont-interation",
      "iconfont iconfont-check-square",
      "iconfont iconfont-insertrowleft",
      "iconfont iconfont-border",
      "iconfont iconfont-translate",
      "iconfont iconfont-border-outer",
      "iconfont iconfont-deleterow",
      "iconfont iconfont-border-top",
      "iconfont iconfont-border-bottom",
      "iconfont iconfont-Field-number",
      "iconfont iconfont-border-left",
      "iconfont iconfont-Field-String",
      "iconfont iconfont-border-right",
      "iconfont iconfont-Function",
      "iconfont iconfont-border-inner",
      "iconfont iconfont-Field-time",
      "iconfont iconfont-border-verticle",
      "iconfont iconfont-GIF",
      "iconfont iconfont-border-horizontal",
      "iconfont iconfont-Partition",
      "iconfont iconfont-radius-bottomleft",
      "iconfont iconfont-index",
      "iconfont iconfont-radius-bottomright",
      "iconfont iconfont-Storedprocedure",
      "iconfont iconfont-radius-upleft",
      "iconfont iconfont-Field-Binary",
      "iconfont iconfont-radius-upright",
      "iconfont iconfont-Console-SQL",
      "iconfont iconfont-radius-setting",
      "iconfont iconfont-icon-test",
      "iconfont iconfont-adduser",
      "iconfont iconfont-aim",
      "iconfont iconfont-deleteteam",
      "iconfont iconfont-compress",
      "iconfont iconfont-deleteuser",
      "iconfont iconfont-expend",
      "iconfont iconfont-addteam",
      "iconfont iconfont-folder-view",
      "iconfont iconfont-user",
      "iconfont iconfont-file-GIF",
      "iconfont iconfont-team",
      "iconfont iconfont-group",
      "iconfont iconfont-send",
      "iconfont iconfont-linechart",
      "iconfont iconfont-Report",
      "iconfont iconfont-barchart",
      "iconfont iconfont-View",
      "iconfont iconfont-pointmap",
      "iconfont iconfont-shortcut",
      "iconfont iconfont-container",
      "iconfont iconfont-ungroup",
      "iconfont iconfont-database",
      "iconfont iconfont-sever",
      "iconfont iconfont-mobile",
      "iconfont iconfont-tablet",
      "iconfont iconfont-redenvelope",
      "iconfont iconfont-book",
      "iconfont iconfont-filedone",
      "iconfont iconfont-reconciliation",
      "iconfont iconfont-file-exception",
      "iconfont iconfont-filesync",
      "iconfont iconfont-filesearch",
      "iconfont iconfont-solution",
      "iconfont iconfont-fileprotect",
      "iconfont iconfont-file-add",
      "iconfont iconfont-file-excel",
      "iconfont iconfont-file-exclamation",
      "iconfont iconfont-file-pdf",
      "iconfont iconfont-file-image",
      "iconfont iconfont-file-markdown",
      "iconfont iconfont-file-unknown",
      "iconfont iconfont-file-ppt",
      "iconfont iconfont-file-word",
      "iconfont iconfont-file",
      "iconfont iconfont-file-zip",
      "iconfont iconfont-file-text",
      "iconfont iconfont-file-copy",
      "iconfont iconfont-snippets",
      "iconfont iconfont-audit",
      "iconfont iconfont-diff",
      "iconfont iconfont-Batchfolding",
      "iconfont iconfont-securityscan",
      "iconfont iconfont-propertysafety",
      "iconfont iconfont-safetycertificate",
      "iconfont iconfont-insurance",
      "iconfont iconfont-alert",
      "iconfont iconfont-delete",
      "iconfont iconfont-hourglass",
      "el-icon-delete",
      "el-icon-setting",
      "el-icon-user",
      "el-icon-phone-outline",
      "el-icon-more-outline",
      "el-icon-star-off",
      "el-icon-goods",
      "el-icon-warning-outline",
      "el-icon-zoom-in",
      "el-icon-zoom-out",
      "el-icon-remove-outline",
      "el-icon-circle-plus-outline",
      "el-icon-circle-check",
      "el-icon-circle-close",
      "el-icon-minus",
      "el-icon-plus",
      "el-icon-check",
      "el-icon-close",
      "el-icon-picture-outline",
      "el-icon-picture-outline-round",
      "el-icon-upload2",
      "el-icon-download",
      "el-icon-camera",
      "el-icon-video-camera",
      "el-icon-bell",
      "el-icon-bottom-left",
      "el-icon-bottom-right",
      "el-icon-back",
      "el-icon-right",
      "el-icon-bottom",
      "el-icon-top",
      "el-icon-top-left",
      "el-icon-top-right",
      "el-icon-arrow-left",
      "el-icon-arrow-right",
      "el-icon-arrow-down",
      "el-icon-arrow-up",
      "el-icon-d-arrow-left",
      "el-icon-d-arrow-right",
      "el-icon-video-pause",
      "el-icon-video-play",
      "el-icon-refresh",
      "el-icon-refresh-right",
      "el-icon-refresh-left",
      "el-icon-finished",
      "el-icon-sort",
      "el-icon-sort-up",
      "el-icon-sort-down",
      "el-icon-rank",
      "el-icon-loading",
      "el-icon-view",
      "el-icon-c-scale-to-original",
      "el-icon-date",
      "el-icon-edit",
      "el-icon-edit-outline",
      "el-icon-folder",
      "el-icon-folder-opened",
      "el-icon-folder-add",
      "el-icon-folder-remove",
      "el-icon-folder-delete",
      "el-icon-folder-checked",
      "el-icon-tickets",
      "el-icon-document-remove",
      "el-icon-document-delete",
      "el-icon-document-copy",
      "el-icon-document-checked",
      "el-icon-document",
      "el-icon-document-add",
      "el-icon-printer",
      "el-icon-paperclip",
      "el-icon-takeaway-box",
      "el-icon-search",
      "el-icon-monitor",
      "el-icon-attract",
      "el-icon-mobile",
      "el-icon-scissors",
      "el-icon-umbrella",
      "el-icon-headset",
      "el-icon-brush",
      "el-icon-mouse",
      "el-icon-coordinate",
      "el-icon-magic-stick",
      "el-icon-reading",
      "el-icon-data-line",
      "el-icon-data-board",
      "el-icon-pie-chart",
      "el-icon-data-analysis",
      "el-icon-collection-tag",
      "el-icon-film",
      "el-icon-suitcase",
      "el-icon-suitcase-1",
      "el-icon-receiving",
      "el-icon-collection",
      "el-icon-files",
      "el-icon-notebook-1",
      "el-icon-notebook-2",
      "el-icon-toilet-paper",
      "el-icon-office-building",
      "el-icon-school",
      "el-icon-table-lamp",
      "el-icon-house",
      "el-icon-no-smoking",
      "el-icon-smoking",
      "el-icon-shopping-cart-full",
      "el-icon-shopping-cart-1",
      "el-icon-shopping-cart-2",
      "el-icon-shopping-bag-1",
      "el-icon-shopping-bag-2",
      "el-icon-sold-out",
      "el-icon-sell",
      "el-icon-present",
      "el-icon-box",
      "el-icon-bank-card",
      "el-icon-money",
      "el-icon-coin",
      "el-icon-wallet",
      "el-icon-discount",
      "el-icon-price-tag",
      "el-icon-news",
      "el-icon-guide",
      "el-icon-male",
      "el-icon-female",
      "el-icon-thumb",
      "el-icon-cpu",
      "el-icon-link",
      "el-icon-connection",
      "el-icon-open",
      "el-icon-turn-off",
      "el-icon-set-up",
      "el-icon-chat-round",
      "el-icon-chat-line-round",
      "el-icon-chat-square",
      "el-icon-chat-dot-round",
      "el-icon-chat-dot-square",
      "el-icon-chat-line-square",
      "el-icon-message",
      "el-icon-postcard",
      "el-icon-position",
      "el-icon-turn-off-microphone",
      "el-icon-microphone",
      "el-icon-close-notification",
      "el-icon-bangzhu",
      "el-icon-time",
      "el-icon-odometer",
      "el-icon-crop",
      "el-icon-aim",
      "el-icon-switch-button",
      "el-icon-full-screen",
      "el-icon-copy-document",
      "el-icon-mic",
      "el-icon-stopwatch",
      "el-icon-medal-1",
      "el-icon-medal",
      "el-icon-trophy",
      "el-icon-trophy-1",
      "el-icon-first-aid-kit",
      "el-icon-discover",
      "el-icon-place",
      "el-icon-location-outline",
      "el-icon-location-information",
      "el-icon-add-location",
      "el-icon-delete-location",
      "el-icon-map-location",
      "el-icon-alarm-clock",
      "el-icon-timer",
      "el-icon-watch-1",
      "el-icon-watch",
      "el-icon-lock",
      "el-icon-unlock",
      "el-icon-key",
      "el-icon-service",
      "el-icon-mobile-phone",
      "el-icon-bicycle",
      "el-icon-truck",
      "el-icon-ship",
      "el-icon-basketball",
      "el-icon-football",
      "el-icon-soccer",
      "el-icon-baseball",
      "el-icon-wind-power",
      "el-icon-light-rain",
      "el-icon-lightning",
      "el-icon-heavy-rain",
      "el-icon-sunrise",
      "el-icon-sunrise-1",
      "el-icon-sunset",
      "el-icon-sunny",
      "el-icon-cloudy",
      "el-icon-partly-cloudy",
      "el-icon-cloudy-and-sunny",
      "el-icon-moon",
      "el-icon-moon-night",
      "el-icon-dish",
      "el-icon-dish-1",
      "el-icon-food",
      "el-icon-chicken",
      "el-icon-fork-spoon",
      "el-icon-knife-fork",
      "el-icon-burger",
      "el-icon-tableware",
      "el-icon-sugar",
      "el-icon-dessert",
      "el-icon-ice-cream",
      "el-icon-hot-water",
      "el-icon-water-cup",
      "el-icon-coffee-cup",
      "el-icon-cold-drink",
      "el-icon-goblet",
      "el-icon-goblet-full",
      "el-icon-goblet-square",
      "el-icon-goblet-square-full",
      "el-icon-refrigerator",
      "el-icon-grape",
      "el-icon-watermelon",
      "el-icon-cherry",
      "el-icon-apple",
      "el-icon-pear",
      "el-icon-orange",
      "el-icon-coffee",
      "el-icon-ice-tea",
      "el-icon-ice-drink",
      "el-icon-milk-tea",
    ]
  },
  {
    label: "系统图标",
    list: [
      "el-icon-delete",
      "el-icon-setting",
      "el-icon-user",
      "el-icon-phone-outline",
      "el-icon-more-outline",
      "el-icon-star-off",
      "el-icon-goods",
      "el-icon-warning-outline",
      "el-icon-zoom-in",
      "el-icon-zoom-out",
      "el-icon-remove-outline",
      "el-icon-circle-plus-outline",
      "el-icon-circle-check",
      "el-icon-circle-close",
      "el-icon-minus",
      "el-icon-plus",
      "el-icon-check",
      "el-icon-close",
      "el-icon-picture-outline",
      "el-icon-picture-outline-round",
      "el-icon-upload2",
      "el-icon-download",
      "el-icon-camera",
      "el-icon-video-camera",
      "el-icon-bell",
      "el-icon-bottom-left",
      "el-icon-bottom-right",
      "el-icon-back",
      "el-icon-right",
      "el-icon-bottom",
      "el-icon-top",
      "el-icon-top-left",
      "el-icon-top-right",
      "el-icon-arrow-left",
      "el-icon-arrow-right",
      "el-icon-arrow-down",
      "el-icon-arrow-up",
      "el-icon-d-arrow-left",
      "el-icon-d-arrow-right",
      "el-icon-video-pause",
      "el-icon-video-play",
      "el-icon-refresh",
      "el-icon-refresh-right",
      "el-icon-refresh-left",
      "el-icon-finished",
      "el-icon-sort",
      "el-icon-sort-up",
      "el-icon-sort-down",
      "el-icon-rank",
      "el-icon-loading",
      "el-icon-view",
      "el-icon-c-scale-to-original",
      "el-icon-date",
      "el-icon-edit",
      "el-icon-edit-outline",
      "el-icon-folder",
      "el-icon-folder-opened",
      "el-icon-folder-add",
      "el-icon-folder-remove",
      "el-icon-folder-delete",
      "el-icon-folder-checked",
      "el-icon-tickets",
      "el-icon-document-remove",
      "el-icon-document-delete",
      "el-icon-document-copy",
      "el-icon-document-checked",
      "el-icon-document",
      "el-icon-document-add",
      "el-icon-printer",
      "el-icon-paperclip",
      "el-icon-takeaway-box",
      "el-icon-search",
      "el-icon-monitor",
      "el-icon-attract",
      "el-icon-mobile",
      "el-icon-scissors",
      "el-icon-umbrella",
      "el-icon-headset",
      "el-icon-brush",
      "el-icon-mouse",
      "el-icon-coordinate",
      "el-icon-magic-stick",
      "el-icon-reading",
      "el-icon-data-line",
      "el-icon-data-board",
      "el-icon-pie-chart",
      "el-icon-data-analysis",
      "el-icon-collection-tag",
      "el-icon-film",
      "el-icon-suitcase",
      "el-icon-suitcase-1",
      "el-icon-receiving",
      "el-icon-collection",
      "el-icon-files",
      "el-icon-notebook-1",
      "el-icon-notebook-2",
      "el-icon-toilet-paper",
      "el-icon-office-building",
      "el-icon-school",
      "el-icon-table-lamp",
      "el-icon-house",
      "el-icon-no-smoking",
      "el-icon-smoking",
      "el-icon-shopping-cart-full",
      "el-icon-shopping-cart-1",
      "el-icon-shopping-cart-2",
      "el-icon-shopping-bag-1",
      "el-icon-shopping-bag-2",
      "el-icon-sold-out",
      "el-icon-sell",
      "el-icon-present",
      "el-icon-box",
      "el-icon-bank-card",
      "el-icon-money",
      "el-icon-coin",
      "el-icon-wallet",
      "el-icon-discount",
      "el-icon-price-tag",
      "el-icon-news",
      "el-icon-guide",
      "el-icon-male",
      "el-icon-female",
      "el-icon-thumb",
      "el-icon-cpu",
      "el-icon-link",
      "el-icon-connection",
      "el-icon-open",
      "el-icon-turn-off",
      "el-icon-set-up",
      "el-icon-chat-round",
      "el-icon-chat-line-round",
      "el-icon-chat-square",
      "el-icon-chat-dot-round",
      "el-icon-chat-dot-square",
      "el-icon-chat-line-square",
      "el-icon-message",
      "el-icon-postcard",
      "el-icon-position",
      "el-icon-turn-off-microphone",
      "el-icon-microphone",
      "el-icon-close-notification",
      "el-icon-bangzhu",
      "el-icon-time",
      "el-icon-odometer",
      "el-icon-crop",
      "el-icon-aim",
      "el-icon-switch-button",
      "el-icon-full-screen",
      "el-icon-copy-document",
      "el-icon-mic",
      "el-icon-stopwatch",
      "el-icon-medal-1",
      "el-icon-medal",
      "el-icon-trophy",
      "el-icon-trophy-1",
      "el-icon-first-aid-kit",
      "el-icon-discover",
      "el-icon-place",
      "el-icon-location-outline",
      "el-icon-location-information",
      "el-icon-add-location",
      "el-icon-delete-location",
      "el-icon-map-location",
      "el-icon-alarm-clock",
      "el-icon-timer",
      "el-icon-watch-1",
      "el-icon-watch",
      "el-icon-lock",
      "el-icon-unlock",
      "el-icon-key",
      "el-icon-service",
      "el-icon-mobile-phone",
      "el-icon-bicycle",
      "el-icon-truck",
      "el-icon-ship",
      "el-icon-basketball",
      "el-icon-football",
      "el-icon-soccer",
      "el-icon-baseball",
      "el-icon-wind-power",
      "el-icon-light-rain",
      "el-icon-lightning",
      "el-icon-heavy-rain",
      "el-icon-sunrise",
      "el-icon-sunrise-1",
      "el-icon-sunset",
      "el-icon-sunny",
      "el-icon-cloudy",
      "el-icon-partly-cloudy",
      "el-icon-cloudy-and-sunny",
      "el-icon-moon",
      "el-icon-moon-night",
      "el-icon-dish",
      "el-icon-dish-1",
      "el-icon-food",
      "el-icon-chicken",
      "el-icon-fork-spoon",
      "el-icon-knife-fork",
      "el-icon-burger",
      "el-icon-tableware",
      "el-icon-sugar",
      "el-icon-dessert",
      "el-icon-ice-cream",
      "el-icon-hot-water",
      "el-icon-water-cup",
      "el-icon-coffee-cup",
      "el-icon-cold-drink",
      "el-icon-goblet",
      "el-icon-goblet-full",
      "el-icon-goblet-square",
      "el-icon-goblet-square-full",
      "el-icon-refrigerator",
      "el-icon-grape",
      "el-icon-watermelon",
      "el-icon-cherry",
      "el-icon-apple",
      "el-icon-pear",
      "el-icon-orange",
      "el-icon-coffee",
      "el-icon-ice-tea",
      "el-icon-ice-drink",
      "el-icon-milk-tea",
    ]
  }
]
