export const options = {
    page: false,
    align: "center",
    menuAlign: "center",
    addBtn: false,
    refreshBtn: false,
    columnBtn: false,
    border: true,
    stripe: true,
    editBtn: false,
    delBtn: true,
    maxHeight: 600,
    menuWidth: 100,
    menuFixed: "right",
    index: true,
    indexLabel: '序号',
    column: [
        {
            prop: "orderNum",
            label: "排序",
            size: "mini",
            cell: true,
        },
        {
            prop: "dbFieldName",
            label: "字段名",
            size: "mini",
            cell: true,
        },
        {
            prop: "dbFieldRemark",
            label: "字段描述",
            size: "mini",
            cell: true,
        },
        {
            prop: "dbType",
            label: "字段类型",
            size: "mini",
            cell: true,
        },
        {
            prop: "dbLength",
            label: "字段长度",
            size: "mini",
            cell: true,
        },
        {
            prop: "dbPointLength",
            label: "小数位",
            size: "mini",
            cell: true,
        },
        {
            prop: "dbIsField",
            label: "是否数据库字段",
            size: "mini",
            cell: true,
        },
        {
            prop: "fieldShow",
            label: "新增可见",
            size: "mini",
            cell: true,
        },
        {
            prop: "fieldAlter",
            label: "新增可改",
            size: "mini",
            cell: true,
        },
        {
            prop: "isRequired",
            label: "新增必填",
            size: "mini",
            cell: true,
        },
        {
            prop: "updateFieldShow",
            label: "修改可见",
            size: "mini",
            cell: true,
        },
        {
            prop: "updateFieldAlter",
            label: "修改可改",
            size: "mini",
            cell: true,
        },
        {
            prop: "updateIsRequired",
            label: "修改必填",
            size: "mini",
            cell: true,
        },
        {
            prop: "displayVisible",
            label: "显示可见",
            size: "mini",
            cell: true,
        },
        {
            prop: "formDefaultValue",
            label: "新建界面默认值",
            size: "mini",
            cell: true,
        },
        {
            prop: "dbDefaultValue",
            label: "保存默认值",
            size: "mini",
            cell: true,
        },
        {
            prop: "formInputType",
            label: "控件类型",
            size: "mini",
            cell: true,
        },
        {
            prop: "isRequired",
            label: "新增必填",
            size: "mini",
            cell: true,
        },
        {
            prop: "isRequired",
            label: "新增必填",
            size: "mini",
            cell: true,
        },
        {
            prop: "isRequired",
            label: "新增必填",
            size: "mini",
            cell: true,
        },
        {
            prop: "isRequired",
            label: "新增必填",
            size: "mini",
            cell: true,
        }
    ],
}